name: github-actions
on: push
jobs:
  accuracy_checker:
    strategy:
      matrix:
        runs-on: [ubuntu-20.04, ubuntu-22.04]
        python-version: [3.8, 3.9, '3.10']
    runs-on: ${{ matrix.runs-on }}
    services:
      pypi_wayback:
        image: ghcr.io/waleko/pypi-wayback
        ports:
        - 8629:8080
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Pip install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tools/accuracy_checker openvino -r tools/accuracy_checker/requirements-test.in
    - name: python -m pytest tools/accuracy_checker
      run: |
        python -m pytest tools/accuracy_checker
    - name: Pip install and run pylint
      working-directory: ./tools/accuracy_checker
      run: |
        python -m pip install pylint==2.10.2
        PYTHONPATH=. python -m pylint --rcfile=.pylintrc `find -wholename '?*/**/*.py' -not -path "./tests/*" -not -path "./build/*"`

env:
  PIP_INDEX_URL: http://localhost:8629/2023-12-01
  UV_INDEX_URL: http://localhost:8629/2023-12-01
